### ISSUE TITLE
Stack definition

### ISSUE THREAD

**Issue by ErickSaito** [ErickSaito/MC855#2]
React Native TS

Firebase
- Cloud Messaging

Node TS -> Nest
AWS - Free tier
- ECS

API de clima: https://openweathermap.org/api

**Comment by paulopacitti** [comment]
Architecture sketch made in 2022-08-23T17:24:58-03:00
![Image](https://user-images.githubusercontent.com/18006523/186258635-c786ff78-f1d7-4c28-b808-52ab36fdf183.jpg)
