### ISSUE TITLE
Build push notifications infrastructure

### ISSUE THREAD

**Issue by Fabio-Ricci** [ErickSaito/MC855#38]
- [x] Create firebase project
- [x] Add app keys and configurations to firebase
- [x] Add firebase keys and configurations to app

**Comment by paulopacitti** [comment]
Created `m855-umbrella` project in Firebase and added e170578@dac.unicamp.br and f170781@dac.unicamp.br to it.

**Comment by paulopacitti** [comment]
Done on #46
